### ISSUE TITLE
Novo filtro para o Skip por Banco de Dados

### ISSUE THREAD

**Issue by dgo-angelo** [totvs/tlpp-probat-samples#1]
#### Descrição da melhoria
Incluir um novo filtro por banco de dados

#### Caso de uso
Esta melhoria permitiria pular um teste de acordo com o banco de dados especificado

#### Informações adicionais
Exemplo:
```
@Skip( database="POSTGRES" ) 
```

**Comment by ricardoclima** [comment]
Este filtro seria interessante, e já estamos criando uma issue interna (DTTLPP-2707) para estudo futuro.

**Comment by denardi-totvs** [comment]
@dgo-angelo 
Recurso implementado e será disponibilizado a partir do tlppCore 01.04.10, ainda sem previsão de data para a expedição.

Obrigado pela sugestão!
